/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import javax.swing.JOptionPane;
import modelo.ProdutoVO;

/**
 *
 * @author Camila_Camera
 */
public class GUICadastrarProd extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUICadastroProd
     */
    public GUICadastrarProd() {
        initComponents();
    }
    
    public void cadastrarProduto () {
        try{
            modelo.ProdutoVO p = new ProdutoVO();
            p.setNome(jtfNomeProduto.getText());
            p.setQuantidade(Integer.parseInt(jtfQuantidadeProd.getText()));
            p.setValorCusto(Double.parseDouble(jtfValorProd.getText()));
        
            //chama o produto servicos, que fará a inserção dos dados da classe dentro do banco
            servicos.ProdutoServicos ps = servicos.ServicosFactory.getProdutoServicos();
            ps.cadastrarProduto(p);
            JOptionPane.showMessageDialog(null, "Seu produto foi cadasatrado com sucesso!", "Confirmação", JOptionPane.INFORMATION_MESSAGE);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Ops, algo deu errado!" +e.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void cancelarProduto() {
        jtfNomeProduto.setText(null);
        jtfQuantidadeProd.setText(null);
        jtfValorProd.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGUICadProd = new javax.swing.JPanel();
        jlNomeProd = new javax.swing.JLabel();
        jlValorProd = new javax.swing.JLabel();
        jlQuantidadeProd = new javax.swing.JLabel();
        jtfNomeProduto = new javax.swing.JTextField();
        jtfValorProd = new javax.swing.JTextField();
        jtfQuantidadeProd = new javax.swing.JTextField();
        jbCadastrar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();

        setClosable(true);

        jPanelGUICadProd.setForeground(new java.awt.Color(102, 255, 204));

        jlNomeProd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlNomeProd.setText("Nome do Produto:");

        jlValorProd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlValorProd.setText("Valor do Produto:");

        jlQuantidadeProd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlQuantidadeProd.setText("Quantidade:");

        jtfNomeProduto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jtfValorProd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jtfQuantidadeProd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jbCadastrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelGUICadProdLayout = new javax.swing.GroupLayout(jPanelGUICadProd);
        jPanelGUICadProd.setLayout(jPanelGUICadProdLayout);
        jPanelGUICadProdLayout.setHorizontalGroup(
            jPanelGUICadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGUICadProdLayout.createSequentialGroup()
                .addGroup(jPanelGUICadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGUICadProdLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanelGUICadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNomeProd)
                            .addComponent(jlValorProd)
                            .addComponent(jlQuantidadeProd))
                        .addGap(124, 124, 124)
                        .addGroup(jPanelGUICadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfNomeProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                            .addComponent(jtfValorProd)
                            .addComponent(jtfQuantidadeProd)))
                    .addGroup(jPanelGUICadProdLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jbCadastrar)
                        .addGap(200, 200, 200)
                        .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanelGUICadProdLayout.setVerticalGroup(
            jPanelGUICadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGUICadProdLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanelGUICadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomeProd)
                    .addComponent(jtfNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(jPanelGUICadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlValorProd)
                    .addComponent(jtfValorProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanelGUICadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlQuantidadeProd)
                    .addComponent(jtfQuantidadeProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(jPanelGUICadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrar)
                    .addComponent(jbCancelar))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGUICadProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelGUICadProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        cancelarProduto();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        cadastrarProduto();
        cancelarProduto();
    }//GEN-LAST:event_jbCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelGUICadProd;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JLabel jlNomeProd;
    private javax.swing.JLabel jlQuantidadeProd;
    private javax.swing.JLabel jlValorProd;
    private javax.swing.JTextField jtfNomeProduto;
    private javax.swing.JTextField jtfQuantidadeProd;
    private javax.swing.JTextField jtfValorProd;
    // End of variables declaration//GEN-END:variables
}
